SELECT 
	[TABLE_SCHEMA] + '.' + [TABLE_NAME] AS [Table and Schema],
	[COLUMN_NAME] AS [Column Name],
	[DATA_TYPE] AS [Type],
	[COLUMN_DEFAULT] AS [Default],
	[IS_NULLABLE] AS [Nullable],
	[CHARACTER_MAXIMUM_LENGTH] AS [Length],
	[NUMERIC_PRECISION] AS [Precision]	
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMNPROPERTY(object_id(TABLE_NAME), COLUMN_NAME, 'IsIdentity') = 1
ORDER BY TABLE_NAME